name: Bug Report
description: Template for reporting bugs or errors.
title: "[Bug] Title of the Bug"
labels: ["🐞bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Please fill out the information below to help us address the issue.

  - type: input
    id: bug_summary
    attributes:
      label: Bug Summary
      description: Briefly describe the bug.
      placeholder: "Enter a brief summary of the bug"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Description
      description: Provide a detailed description of the bug, including steps to reproduce.
      placeholder: "Enter detailed bug information here"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Specify the environment where the bug occurred (e.g., OS, library versions).
      placeholder: "e.g., Windows 10, Python 3.8, AutoGluon 0.6.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Paste any relevant logs or error messages.
      placeholder: "Enter logs or error messages here"
    validations:
      required: false
